# Help text for `tgt scenario`. Extracted so `_tgt_scenario_cli` and
# the gum-driven menu can both fall back to it.
function _tgt_scenario_help
    echo ""
    echo "  tgt scenario — manage engagement / lab scenarios"
    echo ""
    echo "    tgt scenario new <name>      Create a new scenario, switch to it"
    echo "    tgt scenario list [--all|--archived]"
    echo "                                 List scenarios (active by default; --all"
    echo "                                 includes archived; --archived shows only those)"
    echo "    tgt scenario show [name]     Show scenario details"
    echo "    tgt scenario switch [--all] [name]"
    echo "                                 Make a scenario active (no-arg → fzf;"
    echo "                                 --all to include archived in the picker)"
    echo "    tgt scenario unload          Clear all TGT_* runtime (scenario / target /"
    echo "                                 cred / DC). Nothing on disk is removed."
    echo "    tgt scenario archive [name]  Hide a scenario from the default list"
    echo "    tgt scenario unarchive [name] Surface an archived scenario again"
    echo "    tgt scenario import <path> [--copy] [--dry-run] [--prefix <p>]"
    echo "                                 Bulk-import each subdir under <path> as a"
    echo "                                 scenario; moves the dir into the workspace"
    echo "                                 root (or copies with --copy)."
    echo "    tgt scenario rename [<old>] <new>"
    echo "                                 Rename a scenario (or the active one)."
    echo "                                 Updates /etc/hosts tags + workspace folder."
    echo "    tgt scenario rm <name> [--purge-workspace]"
    echo "                                 Delete a scenario + its /etc/hosts entries."
    echo "                                 With --purge-workspace, also rm -rf its folder."
    echo ""
end
