# Dispatch for `tgt prompt <subcommand>`. Called from tgt.fish.
function _tgt_prompt_cli
    set -l sub $argv[1]
    set -l rest $argv[2..]

    switch "$sub"
        case "" -h --help
            echo ""
            echo "  tgt prompt — manage the [scenario:target] prompt segment"
            echo ""
            echo "    tgt prompt install [--right|--left] [--force]"
            echo "                                Generate fish_(right_)prompt that calls tgt_prompt."
            echo "                                Default slot: --right (less invasive)."
            echo "    tgt prompt uninstall        Remove the managed prompt file(s)"
            echo "    tgt prompt status           Show what's installed"
            echo ""
            echo "  An existing custom prompt file is left alone unless --force is"
            echo "  passed; --force backs it up to <file>.tgt-bak first."
            echo ""
            return 0

        case install
            argparse --name='tgt prompt install' 'r/right' 'l/left' 'f/force' -- $rest
            or return 1

            if set -q _flag_left; and set -q _flag_right
                echo "tgt prompt install: --left and --right are mutually exclusive" >&2
                return 1
            end

            set -l slot right
            set -q _flag_left; and set slot left

            set -l fname fish_right_prompt
            test "$slot" = left; and set fname fish_prompt

            set -l dir (_tgt_fish_functions_dir)
            if not mkdir -p $dir
                echo "tgt prompt install: cannot create $dir" >&2
                return 1
            end
            set -l file "$dir/$fname.fish"

            if test -e $file
                if string match -rq '# tgt-prompt:managed' -- (cat $file)
                    echo "tgt prompt: already installed at $file"
                    return 0
                end
                if not set -q _flag_force
                    echo "tgt prompt install: $file already exists and is not managed by tgt." >&2
                    echo "  Either add 'tgt_prompt' to it by hand, or rerun with --force" >&2
                    echo "  (your existing file will be backed up to $file.tgt-bak)." >&2
                    return 1
                end
                if not command cp -- $file "$file.tgt-bak"
                    echo "tgt prompt install: failed to back up $file" >&2
                    return 1
                end
                echo "✓ backed up $file → $file.tgt-bak"
            end

            printf '%s\n' \
                '# tgt-prompt:managed — generated by `tgt prompt install`.' \
                '# Remove via `tgt prompt uninstall`.' \
                "function $fname" \
                '    tgt_prompt' \
                'end' > $file
            or begin
                echo "tgt prompt install: failed to write $file" >&2
                return 1
            end

            echo "✓ installed at $file (slot: $slot)"
            echo "  Open a new fish shell to see it."
            return 0

        case uninstall
            set -l dir (_tgt_fish_functions_dir)
            set -l removed 0
            for fname in fish_prompt fish_right_prompt
                set -l file "$dir/$fname.fish"
                test -e $file; or continue
                if string match -rq '# tgt-prompt:managed' -- (cat $file)
                    if not command rm -- $file
                        echo "tgt prompt uninstall: failed to remove $file" >&2
                        return 1
                    end
                    echo "✓ removed $file"
                    set removed (math $removed + 1)
                end
            end
            if test $removed -eq 0
                echo "tgt prompt: nothing to uninstall (no managed prompt file found)"
            end
            return 0

        case status
            set -l dir (_tgt_fish_functions_dir)
            set -l found 0
            for fname in fish_prompt fish_right_prompt
                set -l file "$dir/$fname.fish"
                if test -e $file
                    if string match -rq '# tgt-prompt:managed' -- (cat $file)
                        echo "  $fname → $file (managed by tgt)"
                        set found (math $found + 1)
                    else
                        echo "  $fname → $file (custom, not managed by tgt)"
                    end
                end
            end
            if test $found -eq 0
                echo "  tgt prompt segment not installed."
                echo "  Run: tgt prompt install [--right|--left]"
            end
            return 0

        case '*'
            echo "tgt prompt: unknown subcommand '$sub'" >&2
            echo "Try: tgt prompt --help" >&2
            return 1
    end
end
